version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: openmrs
      MYSQL_DATABASE: openmrs
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: openmrs
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d/

  openmrs:
      build: .
      image: intelehealth-openmrs:1.0
      restart: "unless-stopped"
      container_name: openmrs
      ports:
         - "9876:8080"
      command: /bin/bash -c "/root/tomcatStart.sh && tail -f /opt/tomcat8/logs/catalina.out"

      depends_on:
         - mysql

volumes:
  db_data: